# python plotting of fields in Warp
# March 30 2018
#first plot 2d of fields with contours or color
#
winon()
pfzx(fill=1, filled=1, plotselfe=2, comp='E', titles=0,cmin=0, cmax=1e6)
fma()
winon(1)
pfzx()
fma
fma()
pfzx(fill=1, filled=1, plotselfe=2, comp='E', titles=0,cmin=0, cmax=1e6)
fma()
pfzx()
fma()
pfzx(fill=1, filled=1, plotselfe=2, comp='E')
fma()
pfzx(comp='E')
fma()
pfzx(plotselfe=1)
fma()
pfzx(plotselfe=1,plotphi=0)
fma()
pfzx(plotselfe=1,plotphi=0,filled=1)
fma()
pfzx(plotselfe=1,plotphi=0,fill=1)
fma()
pfzx(plotselfe=0,plotphi=1,fill=1)
fma()
pfzx(fill=1)
fma()
pfzx(fill=1,filled=1)
fma()
pfzx(fill=1,filled=1,cmin=0,cmax=1000)
fma()
#
#next, plot field component or potential vs a coordinate (eg, Ez vs z)
winon(13)
plp(solver.getez()[solver.ix_axis,:], solver.zmesh)
fma()
plt.imshow(b,origin='lower')
plt.show()
plt.imshow(b,origin='lower')
plt.colorbar()
plt.show()
plt.imshow(a,origin='lower')
plt.colorbar()
plt.show()
winon(13)
winon(14)
pfzx()
fma()
winon(15)
plg(solver.getez()[16,:], solver.zmesh,label=True)
plg(solver.getez()[16,:], solver.zmesh,labels=True)

